files: \.py$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", --line-length=120]

  # black
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
        language_version: python3.9

  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making flake8 line length compatible with black
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E266,E501,W503"
